services:
    
    lom.twig.lom_userextension:
        class: LOCKSSOMatic\UserBundle\Twig\UsersExtension
        arguments: [@doctrine]
        tags:
            - { name: twig.extension }

    lom_user.profile.form.type:
        class: LOCKSSOMatic\UserBundle\Form\Type\ProfileFormType
        arguments: [ LOCKSSOMatic\UserBundle\Entity\User ]
        tags:
            - { name: form.type, alias: lom_user_profile }

    lom.access:
        class: LOCKSSOMatic\UserBundle\Security\Services\Access
        arguments: [@security.context, @problematic.acl_manager, @security.acl.provider]
        tags:
            - { name: acl.check }
