auproperties:
    path:     /
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:AuProperties:index" }

auproperties_show:
    path:     /{id}/show
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:AuProperties:show" }

auproperties_new:
    path:     /new
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:AuProperties:new" }

auproperties_create:
    path:     /create
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:AuProperties:create" }
    requirements: { _method: post }

auproperties_edit:
    path:     /{id}/edit
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:AuProperties:edit" }

auproperties_update:
    path:     /{id}/update
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:AuProperties:update" }
    requirements: { _method: post|put }

auproperties_delete:
    path:     /{id}/delete
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:AuProperties:delete" }
    requirements: { _method: post|delete }
