aus:
    path:     /
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Aus:index" }

aus_show:
    path:     /{id}/show
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Aus:show" }

aus_new:
    path:     /new
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Aus:new" }

aus_create:
    path:     /create
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Aus:create" }
    requirements: { _method: post }

aus_edit:
    path:     /{id}/edit
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Aus:edit" }

aus_update:
    path:     /{id}/update
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Aus:update" }
    requirements: { _method: post|put }

aus_delete:
    path:     /{id}/delete
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Aus:delete" }
    requirements: { _method: post|delete }
