aus:
    pattern:  /
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Aus:index" }

aus_show:
    pattern:  /{id}/show
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Aus:show" }

aus_new:
    pattern:  /new
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Aus:new" }

aus_create:
    pattern:  /create
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Aus:create" }
    requirements: { _method: post }

aus_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Aus:edit" }

aus_update:
    pattern:  /{id}/update
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Aus:update" }
    requirements: { _method: post|put }

aus_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Aus:delete" }
    requirements: { _method: post|delete }
