boxes:
    path:     /
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Boxes:index" }

boxes_show:
    path:     /{id}/show
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Boxes:show" }

boxes_new:
    path:     /new
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Boxes:new" }

boxes_create:
    path:     /create
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Boxes:create" }
    requirements: { _method: post }

boxes_edit:
    path:     /{id}/edit
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Boxes:edit" }

boxes_update:
    path:     /{id}/update
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Boxes:update" }
    requirements: { _method: post|put }

boxes_delete:
    path:     /{id}/delete
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Boxes:delete" }
    requirements: { _method: post|delete }
