boxstatus:
    path:     /
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:BoxStatus:index" }

boxstatus_show:
    path:     /{id}/show
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:BoxStatus:show" }
