content:
    pattern:  /
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Content:index" }

content_show:
    pattern:  /{id}/show
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Content:show" }



