contentproviders:
    path:     /
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:ContentProviders:index" }

contentproviders_show:
    path:     /{id}/show
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:ContentProviders:show" }

contentproviders_new:
    path:     /new
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:ContentProviders:new" }

contentproviders_create:
    path:     /create
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:ContentProviders:create" }
    requirements: { _method: post }

contentproviders_edit:
    path:     /{id}/edit
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:ContentProviders:edit" }

contentproviders_update:
    path:     /{id}/update
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:ContentProviders:update" }
    requirements: { _method: post|put }

contentproviders_delete:
    path:     /{id}/delete
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:ContentProviders:delete" }
    requirements: { _method: post|delete }
