contentowners:
    path:     /
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:ContentOwners:index" }

contentowners_show:
    path:     /{id}/show
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:ContentOwners:show" }

contentowners_new:
    path:     /new
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:ContentOwners:new" }

contentowners_create:
    path:     /create
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:ContentOwners:create" }
    requirements: { _method: post }

contentowners_edit:
    path:     /{id}/edit
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:ContentOwners:edit" }

contentowners_update:
    path:     /{id}/update
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:ContentOwners:update" }
    requirements: { _method: post|put }

contentowners_delete:
    path:     /{id}/delete
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:ContentOwners:delete" }
    requirements: { _method: post|delete }
