content:
    path:     /
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Content:index" }

content_show:
    path:     /{id}/show
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Content:show" }
