deposits:
    pattern:  /
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Deposits:index" }

deposits_show:
    pattern:  /{id}/show
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Deposits:show" }



