lomsettings_edit:
    pattern:  /edit
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:LomSettings:edit" }

lomsettings_update:
    pattern:  /update
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:LomSettings:update" }
    requirements: { _method: post|put }

lomsettings_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:LomSettings:nonexistentcontroller" }
    requirements: { _method: post|delete }

