plnproperties:
    path:     /
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:PlnProperties:index" }

plnproperties_show:
    path:     /{id}/show
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:PlnProperties:show" }

plnproperties_new:
    path:     /new
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:PlnProperties:new" }

plnproperties_create:
    path:     /create
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:PlnProperties:create" }
    requirements: { _method: post }

plnproperties_edit:
    path:     /{id}/edit
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:PlnProperties:edit" }

plnproperties_update:
    path:     /{id}/update
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:PlnProperties:update" }
    requirements: { _method: post|put }

plnproperties_delete:
    path:     /{id}/delete
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:PlnProperties:delete" }
    requirements: { _method: post|delete }
