plns:
    path:     /
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Plns:index" }

plns_show:
    path:     /{id}/show
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Plns:show" }

plns_new:
    path:     /new
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Plns:new" }

plns_create:
    path:     /create
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Plns:create" }
    requirements: { _method: post }

plns_edit:
    path:     /{id}/edit
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Plns:edit" }

plns_update:
    path:     /{id}/update
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Plns:update" }
    requirements: { _method: post|put }

plns_delete:
    path:     /{id}/delete
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Plns:delete" }
    requirements: { _method: post|delete }
