pluginproperties:
    path:     /
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:PluginProperties:index" }

pluginproperties_show:
    path:     /{id}/show
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:PluginProperties:show" }

pluginproperties_new:
    path:     /new
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:PluginProperties:new" }

pluginproperties_create:
    path:     /create
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:PluginProperties:create" }
    requirements: { _method: post }

pluginproperties_edit:
    path:     /{id}/edit
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:PluginProperties:edit" }

pluginproperties_update:
    path:     /{id}/update
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:PluginProperties:update" }
    requirements: { _method: post|put }

pluginproperties_delete:
    path:     /{id}/delete
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:PluginProperties:delete" }
    requirements: { _method: post|delete }
