plugins:
    path:     /
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Plugins:index" }

plugins_show:
    path:     /{id}/show
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Plugins:show" }

plugins_new:
    path:     /new
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Plugins:new" }

plugins_create:
    path:     /create
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Plugins:create" }
    requirements: { _method: post }

plugins_edit:
    path:     /{id}/edit
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Plugins:edit" }

plugins_update:
    path:     /{id}/update
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Plugins:update" }
    requirements: { _method: post|put }

plugins_delete:
    path:     /{id}/delete
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Plugins:delete" }
    requirements: { _method: post|delete }
