LOCKSSOMaticCRUDBundle_plugins:
    resource: "@LOCKSSOMaticCRUDBundle/Resources/config/routing/plugins.yml"
    prefix:   /plugins

LOCKSSOMaticCRUDBundle_pluginproperties:
    resource: "@LOCKSSOMaticCRUDBundle/Resources/config/routing/pluginproperties.yml"
    prefix:   /pluginproperties

LOCKSSOMaticCRUDBundle_plns:
    resource: "@LOCKSSOMaticCRUDBundle/Resources/config/routing/plns.yml"
    prefix:   /plns

LOCKSSOMaticCRUDBundle_plnproperties:
    resource: "@LOCKSSOMaticCRUDBundle/Resources/config/routing/plnproperties.yml"
    prefix:   /plnproperties

LOCKSSOMaticCRUDBundle_externaltitledbs:
    resource: "@LOCKSSOMaticCRUDBundle/Resources/config/routing/externaltitledbs.yml"
    prefix:   /externaltitledbs

LOCKSSOMaticCRUDBundle_deposits:
    resource: "@LOCKSSOMaticCRUDBundle/Resources/config/routing/deposits.yml"
    prefix:   /deposits

LOCKSSOMaticCRUDBundle_contentproviders:
    resource: "@LOCKSSOMaticCRUDBundle/Resources/config/routing/contentproviders.yml"
    prefix:   /contentproviders

LOCKSSOMaticCRUDBundle_contentowners:
    resource: "@LOCKSSOMaticCRUDBundle/Resources/config/routing/contentowners.yml"
    prefix:   /contentowners

LOCKSSOMaticCRUDBundle_content:
    resource: "@LOCKSSOMaticCRUDBundle/Resources/config/routing/content.yml"
    prefix:   /content

LOCKSSOMaticCRUDBundle_boxes:
    resource: "@LOCKSSOMaticCRUDBundle/Resources/config/routing/boxes.yml"
    prefix:   /boxes

LOCKSSOMaticCRUDBundle_boxstatus:
    resource: "@LOCKSSOMaticCRUDBundle/Resources/config/routing/boxstatus.yml"
    prefix:   /boxstatus

LOCKSSOMaticCRUDBundle_aus:
    resource: "@LOCKSSOMaticCRUDBundle/Resources/config/routing/aus.yml"
    prefix:   /aus

LOCKSSOMaticCRUDBundle_austatus:
    resource: "@LOCKSSOMaticCRUDBundle/Resources/config/routing/austatus.yml"
    prefix:   /austatus

LOCKSSOMaticCRUDBundle_auproperties:
    resource: "@LOCKSSOMaticCRUDBundle/Resources/config/routing/auproperties.yml"
    prefix:   /auproperties

