locksso_matic_plugin_lompluginsdata:
    resource: "@LOCKSSOMaticPluginBundle/Resources/config/routing/lompluginsdata.yml"
    prefix:   /lompluginsdata

locksso_matic_plugin_lomplugins:
    resource: "@LOCKSSOMaticPluginBundle/Resources/config/routing/lomplugins.yml"
    prefix:   /lomplugins

locksso_matic_plugin_default:
    resource: "@LOCKSSOMaticPluginBundle/Resources/config/routing/default.yml"
    prefix:     /plugins_manager