imports:
    - { resource: config_dev.yml }

security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: plaintext

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

monolog:
    handlers:
        main:
            level:  warning

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  error
        console:
            type:   console
            bubble: false
            
doctrine:
    dbal:
        # variables are defined in parameters.yml
        host: 127.0.0.1
        dbname: lomtest
        user: lomtest
        password: abc123
