imports:
    - { resource: config_dev.yml }

security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: plaintext

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        # variables are defined in parameters.yml
        host: 127.0.0.1
        dbname: lomtest
        user: lomtest
        password: abc123
