locksso_matic_crud:
    resource: "@LOCKSSOMaticCRUDBundle/Resources/config/routing.yml"
    prefix:   /

locksso_matic_sword:
    resource: "@LOCKSSOMaticSWORDBundle/Resources/config/routing.yml"
    prefix:   /

