security:
    
    acl:
        connection: default
        
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_LOMADMIN: ROLE_USER
        ROLE_ADMIN: ROLE_LOMADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true        
            switch_user:  { role: ROLE_ADMIN }
            
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/admin/, role: ROLE_ADMIN }
