admin_user:
    path:     /
    defaults: { _controller: "LOCKSSOMaticUserBundle:AdminUser:index" }

admin_user_show:
    path:     /{id}/show
    defaults: { _controller: "LOCKSSOMaticUserBundle:AdminUser:show" }

admin_user_new:
    path:     /new
    defaults: { _controller: "LOCKSSOMaticUserBundle:AdminUser:new" }

admin_user_create:
    path:     /create
    defaults: { _controller: "LOCKSSOMaticUserBundle:AdminUser:create" }
    requirements: { _method: post }

admin_user_edit:
    path:     /{id}/edit
    defaults: { _controller: "LOCKSSOMaticUserBundle:AdminUser:edit" }

admin_user_update:
    path:     /{id}/update
    defaults: { _controller: "LOCKSSOMaticUserBundle:AdminUser:update" }
    requirements: { _method: post|put }

admin_user_delete:
    path:     /{id}/delete
    defaults: { _controller: "LOCKSSOMaticUserBundle:AdminUser:delete" }
    requirements: { _method: post|delete }
