parameters:
#    locksso_matic_pln_importer.example.class: LOCKSSOMatic\PLNImporterBundle\Example

services:
#    locksso_matic_pln_importer.example:
#        class: %locksso_matic_pln_importer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
