parameters:
#    locksso_matic_pln_exporter.example.class: LOCKSSOMatic\PLNExporterBundle\Example

services:
#    locksso_matic_pln_exporter.example:
#        class: %locksso_matic_pln_exporter.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
