parameters:
#    locksso_matic_sword.example.class: LOCKSSOMatic\SWORDBundle\Example

services:
#    locksso_matic_sword.example:
#        class: %locksso_matic_sword.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
