LOCKSSOMatic\CRUDBundle\Entity\AuProperties:
    type: entity
    manyToOne:
        au:
            targetEntity: Aus
            inversedBy: auProperties
            joinColumn:
                name: aus_id
                referencedColumnName: id
                onDelete: cascade
        parent:
            targetEntity: AuProperties
            inversedBy: children
            cascade: [persist]
            joinColumn:
                name: parent_id
                referencedColumnName: id
                onDelete: cascade
    oneToMany:
        children:
            targetEntity: AuProperties
            mappedBy: parent
    table: au_properties
    indexes:
        aus_id_idx:
            columns:
                - aus_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Primary key for this table.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        propertyKey:
            type: string
            length: 255
            nullable: false
            comment: 'AU property key.'
            column: property_key
        propertyValue:
            type: text
            nullable: true
            comment: 'AU property value.'
            column: property_value
