LOCKSSOMatic\CRUDBundle\Entity\Aus:
    type: entity
    oneToMany:
        content:
            targetEntity: Content
            mappedBy: au
        auStatus:
            targetEntity: AuStatus
            mappedBy: au
        auProperties:
            targetEntity: AuProperties
            mappedBy: au
    manyToOne:
        pln:
            targetEntity: Plns
            inversedBy: aus
            joinColumn:
                name: plns_id
                referencedColumnName: id
        plugin:
            targetEntity: Plugins
            inversedBy: aus
            joinColumn:
                name: plugins_id
                referencedColumnName: id                
    table: aus
    indexes:
        plns_id_idx:
            columns:
                - plns_id
        plugins_id_idx:
            columns:
                - plugins_id                
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Primary key for this table.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        plnsId:
            type: integer
            nullable: true
            unsigned: false
            comment: 'Foreign key for the plns table.'
            column: plns_id
        pluginsId:
            type: integer
            nullable: true
            unsigned: false
            comment: 'Foreign key for the plugins table.'
            column: plugins_id
        externalTitleDbsId:
            type: integer
            nullable: true
            unsigned: false
            comment: 'Foreign key for the external_title_dbs table.'
            column: external_title_dbs_id            
        auid:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'The LOCKSS auId. @todo: Explain where this is generated.'
        manifestUrl:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'The LOCKSS manifest URL for the AU.'
            column: manifest_url
        open:
            type: integer
            nullable: true
            unsigned: false
            comment: 'Either 1 (indicating that content should still be added to this AU) or 0 (indicating that it should not).'            
    lifecycleCallbacks: {  }
