LOCKSSOMatic\CRUDBundle\Entity\Aus:
    type: entity
    table: aus
    indexes:
        plns_id_idx:
            columns:
                - plns_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        plnsId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: plns_id
        auid:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        manifestUrl:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: manifest_url
    lifecycleCallbacks: {  }
