LOCKSSOMatic\CRUDBundle\Entity\Boxes:
    type: entity
    oneToMany:
        boxStatus:
            targetEntity: BoxStatus
            mappedBy: box
    manyToOne:
        pln:
            targetEntity: Plns
            inversedBy: boxes
            joinColumn:
                name: plns_id
                referencedColumnName: id
    table: boxes
    indexes:
        plns_id_idx:
            columns:
                - plns_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Primary key for this table.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        hostname:
            type: string
            length: 255
            nullable: true
            fixed: false
            comment: 'The hostname of the LOCKSS box.'
        ipAddress:
            type: string
            length: 16
            nullable: true
            fixed: false
            comment: 'The IP address of the LOCKSS box.'
            column: ip_address
        username:
            type: string
            length: 64
            nullable: true
            fixed: false
            comment: 'The username on this box for the account that can access the box''s API.'
        password:
            type: string
            length: 64
            nullable: true
            fixed: false
            comment: 'The password on this box for the account that can access the box''s API.'
