LOCKSSOMatic\CRUDBundle\Entity\Boxes:
    type: entity
    oneToMany:
        boxStatus:
            targetEntity: BoxStatus
            mappedBy: box
    table: boxes
    indexes:
        plns_id_idx:
            columns:
                - plns_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Primary key for this table.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        plnsId:
            type: integer
            nullable: true
            unsigned: false
            comment: 'Foreign key for the plns table.'
            column: plns_id
        hostname:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'The hostname of the LOCKSS box.'
        ipAddress:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'The IP address of the LOCKSS box.'
            column: ip_address
    lifecycleCallbacks: {  }
