LOCKSSOMatic\CRUDBundle\Entity\BoxStatus:
    type: entity
    manyToOne:
        box:
            targetEntity: Boxes
            inversedBy: boxStatus
            joinColumn:
                name: boxes_id
                referencedColumnName: id
    table: box_status
    indexes:
        boxes_id_idx:
            columns:
                - boxes_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Primary key for this table.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        queryDate:
            type: datetime
            nullable: true
            comment: 'Timestamp indicating when the box was queried.'
            column: query_date
        propertyKey:
            type: string
            length: 255
            nullable: true
            fixed: false
            comment: 'Box property key.'
            column: property_key
        propertyValue:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'Box property value.'
            column: property_value
    lifecycleCallbacks:
            prePersist: [setQueryDate]
