LOCKSSOMatic\CRUDBundle\Entity\ContentOwners:
    type: entity
    oneToMany:
        contentProviders:
            targetEntity: ContentProviders
            mappedBy: contentOwner
    table: content_owners
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        emailAddress:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: email_address
    lifecycleCallbacks: {  }
