LOCKSSOMatic\CRUDBundle\Entity\ContentProviders:
    type: entity
    manyToOne:
        contentOwner:
            targetEntity: ContentOwners
            inversedBy: contentProviders
            joinColumn:
                name: content_owners_id
                referencedColumnName: id
    table: content_providers
    indexes:
        content_owners_id_idx:
            columns:
                - content_owners_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        contentOwnersId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: content_owners_id
        type:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        name:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        ipAddress:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: ip_address
        hostname:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        checksumType:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: checksum_type
        maxFileSize:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: max_file_size
        maxAuSize:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: max_au_size            
    lifecycleCallbacks: {  }
