LOCKSSOMatic\CRUDBundle\Entity\ExternalTitleDbs:
    type: entity
    manyToOne:
        pln:
            targetEntity: Plns
            inversedBy: externalTitleDbs
            joinColumn:
                name: plns_id
                referencedColumnName: id
    table: external_title_dbs
    indexes:
        plns_id_idx:
            columns:
                - plns_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Primary key for this table.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        path:
            type: text
            nullable: false
            comment: 'The filesystem path to the uploaded title db file.'
