LOCKSSOMatic\CRUDBundle\Entity\LomSettings:
    type: entity
    table: lom_settings
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        siteName:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'The name of the LOCKSS-O-Matic instance.'
            column: site_name
        baseUrl:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'The URL of the LOCKSS-O-Matic instance, including the ''http://'' and the path.'            
            column: base_url
        ipAddress:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'The IP address of the LOCKSS-O-Matic instance.'            
            column: ip_address
        pathToUploads:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'The absolute filesystem path to the directory where uploaded files are stored.'            
            column: path_to_uploads
        pathToPlnFiles:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'The absolute filesystem path to the directory where files generated by LOCKSS-O-Matic are written.'            
            column: path_to_pln_files
    lifecycleCallbacks: {  }
