LOCKSSOMatic\CRUDBundle\Entity\PlnProperties:
    type: entity
    table: pln_properties
    indexes:
        plns_id_idx:
            columns:
                - plns_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        plnsId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: plns_id
        parentId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: parent_id
        propertyKey:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: property_key
        propertyValue:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: property_value
    lifecycleCallbacks: {  }
