LOCKSSOMatic\CRUDBundle\Entity\PlnProperties:
    type: entity
    manyToOne:
        pln:
            targetEntity: Plns
            inversedBy: plnProperties
            joinColumn:
                name: plns_id
                referencedColumnName: id
        parent:
            targetEntity: PlnProperties
            inversedBy: children
            joinColumn:
                name: parent_id
                referencedColumnName: id
    oneToMany:
        children:
            targetEntity: PlnProperties
            mappedBy: parent
    table: pln_properties
    indexes:
        plns_id_idx:
            columns:
                - plns_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Primary key for this table.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        propertyKey:
            type: string
            length: 255
            nullable: false
            comment: 'PLN property key.'
            column: property_key
        propertyValue:
            type: text
            nullable: true
            comment: 'PLN property value.'
            column: property_value
