LOCKSSOMatic\CRUDBundle\Entity\PluginProperties:
    type: entity
    manyToOne:
        plugin:
            targetEntity: Plugins
            inversedBy: pluginProperties
            joinColumn:
                name: plugins_id
                referencedColumnName: id
        au:
            targetEntity: Aus
            inversedBy: auProperties
            joinColumn:
                name: aus_id
                referencedColumnName: id
    table: plugin_properties
    indexes:
        aus_id_idx:
            columns:
                - aus_id
        plugins_id_idx:
            columns:
                - plugins_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Primary key for this table.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        pluginsId:
            type: integer
            nullable: true
            unsigned: false
            comment: 'Foreign key for the plugins table.'
            column: plugins_id
        ausId:
            type: integer
            nullable: true
            unsigned: false
            comment: 'Foreign key for the aus table.'
            column: aus_id
        parentId:
            type: integer
            nullable: true
            unsigned: false
            comment: 'id value from this table of the property''s parent property.'
            column: parent_id
        propertyKey:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'Plugin proprety key.'
            column: property_key
        propertyValue:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'Plugin property value.'
            column: property_value
    lifecycleCallbacks: {  }
