LOCKSSOMatic\PluginBundle\Entity\LomPluginsData:
    type: entity
    manyToOne:
        lomPlugin:
            targetEntity: LomPlugins
            inversedBy: lomPlugin
            joinColumn:
                name: lomplugin_id
                referencedColumnName: id                
    table: lom_plugin_data
    indexes:
        domain_index: 
            columns: [ domain ]
        object_index:
            columns: [ objectId ]
        key_index:
            columns: [ key ]
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Primary key for this table.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        domain:
            type: string
            length: 255
            nullable: true
            comment: The domain for the plugin's data.
        objectId:
            type: integer
            nullable: true
            comment: The identifier of the object for the data.
        key:
            type: string
            length: 255
            nullable: false
            comment: The key for accessing the data
        value:
            type: object
            comment: The serialized data for the plugin
            