LOCKSSOMatic\PluginBundle\Entity\LomPluginData:
    type: entity
    table: lom_plugin_data
    indexes:
        domain_index: 
            columns: [ domain ]
        object_index:
            columns: [ objectId ]
        datakey_index:
            columns: [ datakey ]
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Primary key for this table.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        plugin:
            type: string
            length: 255
            nullable: false
            comment: The plugin saving the data.
        domain:
            type: string
            length: 255
            nullable: true
            comment: The domain for the plugin's data.
        objectId:
            type: integer
            nullable: true
            comment: The identifier of the object for the data.
        datakey:
            type: string
            length: 255
            nullable: false
            comment: The key for accessing the data.
        value:
            type: object
            comment: The serialized data for the plugin.
