parameters:
#    locksso_matic_pln_monitor.example.class: LOCKSSOMatic\PLNMonitorBundle\Example

services:
#    locksso_matic_pln_monitor.example:
#        class: %locksso_matic_pln_monitor.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
